"""Vault exclusion rules — what never enters a Batch.

See specs/vault-compiler/spec.md "Vault exclusion list" and
"Vault observation scope".
"""

from __future__ import annotations

from pathlib import Path

EXCLUDED_DIR_NAMES: frozenset[str] = frozenset({".obsidian", ".trash", "node_modules", ".git", "__pycache__"})
# .md/.py is the full observed scope, so it already excludes *.ajson (and
# every other suffix) without a separate check.
OBSERVED_SUFFIXES: frozenset[str] = frozenset({".md", ".py"})


def is_excluded(
    path: Path,
    vault_root: Path,
    *,
    nested_repo_names: frozenset[str] = frozenset(),
) -> bool:
    """Return True if `path` (absolute, under `vault_root`) must never enter a Batch.

    `nested_repo_names` covers the 9 nested git repositories the vault
    contains — vault-specific data (see design.md), passed in rather than
    hardcoded here.

    Also excludes anything outside the observed scope (`.md`/`.py`) — see
    "Vault observation scope".
    """
    relative = path.relative_to(vault_root)
    if relative.suffix not in OBSERVED_SUFFIXES:
        return True
    excluded_names = EXCLUDED_DIR_NAMES | nested_repo_names
    return any(part in excluded_names for part in relative.parts)


def resolve_within_vault(path: Path, vault_root: Path) -> Path | None:
    """Resolve `path` and return it only if it lies under `vault_root`.

    See specs/vault-compiler/spec.md "Vault confinement for every processed
    path". Resolves both `path` and `vault_root` with `strict=False`, so a
    path that doesn't exist yet (e.g. racing a CREATED event) still
    resolves correctly instead of raising. Returns `None` -- rejecting the
    path -- for anything whose resolved real location falls outside the
    resolved vault root, which is what makes this the single check that
    rejects an external symlink regardless of whether `path` itself is a
    symlink, a symlink inside a symlinked directory, or a plain path.

    Pure function: callers decide what a `None` result means for their own
    logging/exclusion bookkeeping, this function never logs.
    """
    resolved_root = vault_root.resolve(strict=False)
    resolved_path = path.resolve(strict=False)
    try:
        resolved_path.relative_to(resolved_root)
    except ValueError:
        return None
    return resolved_path


def sanitize_log_text(text: str, vault_root: Path) -> str:
    """Replace any occurrence of `vault_root`'s absolute path within
    `text` with a `<vault>` marker.

    Some error messages this daemon logs are generated by third-party
    code (e.g. a raw `OSError` string from a missing-file extraction
    failure) and embed a full absolute path rather than the
    vault-relative one this daemon's own code already uses — this is
    the one place that scrubs those before they reach a log line. See
    specs/artifact-lifecycle/spec.md "No confidential values in logs".
    """
    resolved = str(vault_root.resolve(strict=False))
    unresolved = str(vault_root)
    return text.replace(resolved, "<vault>").replace(unresolved, "<vault>")
